export { DESIGN_ARTS_PREVIOUS_YEAR_PART_A_SECTIONS as ENGINEERING_PREVIOUS_YEAR_PART_A_SECTIONS, DESIGN_ARTS_PREVIOUS_YEAR_PART_B_SECTIONS as ENGINEERING_PREVIOUS_YEAR_PART_B_SECTIONS } from "./previousYearDesignArtsSections";

export const ENGINEERING_PREVIOUS_YEAR_PART_A_MAX = 200;
export const ENGINEERING_PREVIOUS_YEAR_PART_B_MAX = 375;
export const ENGINEERING_PREVIOUS_YEAR_GRAND_MAX = 575;
